name: Go
env:
  binary_name: qva
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ${{ env.binary_name }} -v ./main.go help.go 

    - name: artifact upload
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Linux_Binary
        path: ./${{ env.binary_name }}

  FailJob:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3.0.0
      with:
        name: Linux_Binary
        path: ./${{ env.binary_name }}
    - name: execute failed 
      run: ./${{ env.binary_name }}